### PR TITLE
Align types with naming convention

### PR DESCRIPTION
**Pull request by masayag**
Signed-off-by: Moti Asayag <masayag@redhat.com>

### CODE REVIEW

**Comment by eloycoto** [comment]
It was requested by Jakub like this: 

https://github.com/project-flotta/flotta-operator/pull/113#discussion_r815664899

I have no preference here, so it's ok to me :-)

**Comment by masayag** [comment]
> It was requested by Jakub like this:
> 
> [#113 (comment)](https://github.com/project-flotta/flotta-operator/pull/113#discussion_r815664899) [#113 (comment)](https://github.com/project-flotta/flotta-operator/pull/113#discussion_r816977954)
> 

iiuc, the comment referred to the swagger.yaml in which we use snake_case. hence lowercase works fine :-) 
in the CRD the convention we're using is camelCase (should start with lowercase but no underscores)

**Comment by jakub-dzon** [comment]
> > It was requested by Jakub like this:
> > [#113 (comment)](https://github.com/project-flotta/flotta-operator/pull/113#discussion_r815664899) [#113 (comment)](https://github.com/project-flotta/flotta-operator/pull/113#discussion_r816977954)
> 
> iiuc, the comment referred to the swagger.yaml in which we use snake_case. hence lowercase works fine :-) in the CRD the convention we're using is camelCase (should start with lowercase but no underscores)

Exactly.

**Review by jakub-dzon — APPROVED** [review]

**Comment by eloycoto** [comment]
> > > It was requested by Jakub like this:
> > > [#113 (comment)](https://github.com/project-flotta/flotta-operator/pull/113#discussion_r815664899) [#113 (comment)](https://github.com/project-flotta/flotta-operator/pull/113#discussion_r816977954)
> > 
> > 
> > iiuc, the comment referred to the swagger.yaml in which we use snake_case. hence lowercase works fine :-) in the CRD the convention we're using is camelCase (should start with lowercase but no underscores)
> 
> Exactly.

Well, in both files, also in CRD:
https://github.com/project-flotta/flotta-operator/pull/113#discussion_r816977954

**Review by machacekondra — APPROVED** [review]

**Pull request merged**
