### PR TITLE
Harmonize logging with SugaredLogger to avoid wrong formatting

### PR DESCRIPTION
**Pull request by gabriel-farache**
Fix the wrong formatting when using SugaredLogger

Current:
```
2022-06-08T12:51:50.150+0300    INFO    httpapi/main.go:158     cannot verify request:authType0methodGETurl/api/flotta-management/v1/control/07b68c4e41b04cb987ef171766c01147/inerrcannot use register certificate on this resource 
2022-06-08T12:51:50.150+0300    INFO    httpapi/main.go:158     cannot verify request:authType0methodGETurl/api/flotta-management/v1/data/07b68c4e41b04cb987ef171766c01147/inerrcannot use register certificate on this resource 
       2022-06-08T12:51:55.155+0300    INFO    httpapi/main.go:158     cannot verify request:authType0methodGETurl/api/flotta-management/v1/control/07b68c4e41b04cb987ef171766c01147/inerrcannot use register certificate on this resource 
2022-06-08T12:51:55.156+0300    INFO    httpapi/main.go:158     cannot verify request:authType0methodGETurl/api/flotta-management/v1/data/07b68c4e41b04cb987ef171766c01147/inerrcannot use register certificate on this resource 
2022-06-08T12:51:55.411+0300    ERROR   yggdrasil/yggdrasil.go:238      forbiddencan't get target namespace for a device        {"DeviceID": "07b68c4e41b04cb987ef171766c01147"}
```
After fix:
```
2022-06-15T14:39:36.833Z        INFO    workspace/main.go:158   cannot verify request   {"authType": 0, "method": "GET", "url": "/api/flotta-management/v1/control/3251c266033744c088c4e4db3074f7fa/in", "err": "cannot use register certificate on this resource"}
2022-06-15T14:39:41.838Z        INFO    workspace/main.go:158   cannot verify request   {"authType": 0, "method": "GET", "url": "/api/flotta-management/v1/control/3251c266033744c088c4e4db3074f7fa/in", "err": "cannot use register certificate on this resource"}
2022-06-15T14:39:41.838Z        INFO    workspace/main.go:158   cannot verify request   {"authType": 0, "method": "GET", "url": "/api/flotta-management/v1/data/3251c266033744c088c4e4db3074f7fa/in", "err": "cannot use register certificate on this resource"}
2022-06-15T14:39:46.840Z        INFO    workspace/main.go:158   cannot verify request   {"authType": 0, "method": "GET", "url": "/api/flotta-management/v1/data/3251c266033744c088c4e4db3074f7fa/in", "err": "cannot use register certificate on this resource"}
2022-06-15T14:39:46.840Z        INFO    workspace/main.go:158   cannot verify request   {"authType": 0, "method": "GET", "url": "/api/flotta-management/v1/control/3251c266033744c088c4e4db3074f7fa/in", "err": "cannot use register certificate on this resource"}
```

Signed-off-by: Gabriel Farache [gfarache@redhat.com](mailto:gfarache@redhat.com)

### CODE REVIEW

**Comment by eloycoto** [comment]
<3 thanks!

**Comment by pkliczewski** [comment]
looks good to me

**Review by jakub-dzon — APPROVED** [review]

**Review by machacekondra — APPROVED** [review]

**Pull request merged**
