### PR TITLE
Missing generated mock files

### PR DESCRIPTION
**Pull request by gciavarrini**
Signed-off-by: Gloria Ciavarrini <gciavarrini@redhat.com>

### CODE REVIEW

**Comment by eloycoto** [comment]
Something should be changed on the .github actions to include those files, no?

**Comment by gciavarrini** [comment]
> Something should be changed on the .github actions to include those files, no?

@eloycoto 
The files `client/yggdrasil/mock_API.go` and `restapi/mock_YggdrasilAPI.go` were already included (see [commit](https://github.com/project-flotta/flotta-operator/commit/505b3c82966880224ab0f53ebadda6148f936062) ). 
I think that they were excluded by mistake here [Separate operator and edge-api codebases](https://github.com/project-flotta/flotta-operator/commit/ea3692c029028532811b058f79684eac97908d3b) (I'm not completely sure on this, @jakub-dzon am i wrong?)

So I don't think It's necessary to change `.github` actions or am I missing the point?

**Review by masayag — APPROVED** [review]

**Review by pkliczewski — APPROVED** [review]

**Review by jakub-dzon — APPROVED** [review]

**Pull request merged**
