### PR TITLE
Add OWNERS

### PR DESCRIPTION
**Pull request by masayag**
Signed-off-by: Moti Asayag <masayag@redhat.com>

### CODE REVIEW

**Comment by jordigilh** [comment]
Well that sucks, I'm not even a reviewer 😢

**Comment by masayag** [comment]
> Well that sucks, I'm not even a reviewer cry

non intentional :-) you're there now.

**Review by jakub-dzon — APPROVED** [review]

**Comment by jakub-dzon** [comment]
Thank you!

**Review by gciavarrini — APPROVED** [review]

**Review by pkliczewski — APPROVED** [review]

**Pull request merged**
